### PR TITLE
Feature/A-New-Hope -> Develop

### PR DESCRIPTION
**Pull request by notskos**
- Migrated project to use [Git LFS](https://git-lfs.github.com) to store things such as images, audio, textures etc. **Make sure to install Git LFS so that you can pull the files to test it out**.

- Made the ship bounce off the camera edges.

- The ship is also repelled by the edges of the screen, and will be forced towards the middle of the screen if left alone.

### CODE REVIEW

**Comment by notskos** [comment]
[Get an space environment set up with a controllable ship](https://trello.com/c/gozRMgow/2-get-an-space-environment-set-up-with-a-controllable-ship)

**Comment by notskos** [comment]
[Slow down at edges](https://trello.com/c/qdw3ohLp/5-slow-down-at-edges)

**Comment by notskos** [comment]
[Collide at edge](https://trello.com/c/k7lURZnn/6-collide-at-edge)

**Comment by JoshuaMEllis** [comment]
Looks good (y)

**Review by JoshuaMEllis — APPROVED** [review]
Fab

**Pull request merged**
